Feature/5
JeyFol/JeyFolrep pull request #10
Opened 2021-11-18 15:11 UTC by JeyFol

Решена задача 2-1

2021-11-19 23:41 UTC, MarinaPaley requested changes
Она не будет работать

2021-11-19 23:41 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +* \brief ������ ����������
Файл должен быть сохранен в кодировке `UTF-8`

2021-11-19 23:41 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +	int a, b, c{}, choice;
Что такое `c{}`? Для чего?

2021-11-19 23:41 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +	double first(int a, int b ,int c) {
Что должна возвращать данная функция?
Она не будет работать, параметры должны проверить передаваться по ссылке.

2021-11-20 11:09 UTC, JeyFol commented on Task 2/Task 2-1/main.cpp
> +* \brief ������ ����������
Я могу как-нибудь сделать так, чтобы всегда сохранялось в кодировке UTF-8? Или мне самому придётся каждый раз менять кодировку?

2021-11-20 19:24 UTC, MarinaPaley requested changes
Совсем неправильно реализованы функции...Нужно использовать `(int& a, int& b)`

2021-11-20 19:24 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +	std::cout << "Выбрать как выполнить задание:\n1 - с использованием третьей переменной\n2 - без использования третьей переменной\nВыбор: ";
Не используете тип перечисление, а надо. 
У Вас 
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

2021-11-20 19:24 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +
лишние пробелы не нужны

2021-11-20 19:24 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +	return b;
что за зоопарк типов данных?

2021-11-20 19:24 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +	std::swap(a, b);
нужно самому реализовать обмен
и опять же, на входе целый тип данных, а на выходе....вещественный, почему?

2021-11-25 13:15 UTC, MarinaPaley requested changes
здесь проблема с алгоритмизацией
есть 2 варианта решения: сразу выводить в функции переменные, значения которых поменяли (легкий способ), использовать такую сигнатуру `void swap_with_param(int& a, int& b);

2021-12-02 11:26 UTC, MarinaPaley requested changes

2021-12-02 11:26 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +void first(int& a, int& b, int& temp);
зачем `temp`?

2021-12-02 11:26 UTC, MarinaPaley commented on Task 2/Task 2-1/main.cpp
> +	int a, b, temp, choice;
локальные переменные [располагайте в том месте, где используете](https://google.github.io/styleguide/cppguide.html#Local_Variables)

2022-01-02 14:06 UTC, merged